server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: ${GIT_URI:/home/aleksey/IdeaProjects/geekbrains/2022/may/gb-settings-may}
          clone-on-start: true
          username: ${GIT_USERNAME:geek}
          password: ${GIT_PASSWORD:geek}
        default-label: Homework_Lesson4
  security:
    user:
      name: ${SECURITY_USER:geek_user}
      password: ${SECURITY_PASSWORD:geek_pass}
